Repository MIT-Emerging-Talent/ET6-foundations-group-19, pull requests merged in 2025-01, with the labels that each got.

#37 Edit format of individual goals
  collaboration/learning_goals.md
Labels: documentation

#40 Edit heading syntax
  collaboration/communication.md
Labels: documentation

#48 Challenge/Reverse a number
  solutions/__init__.py
  solutions/reversed_positive_number.py
  solutions/tests/__init__.py
  solutions/tests/test_reversed_positive_number.py
Labels: Challenge

#55 Challenge/Sum digits of a positive number
  solutions/sum_digits_of_positive_number.py
  solutions/tests/test_sum_digits_of_positive_number.py
Labels: Challenge

#65 rama first challenge
  solutions/multiplication.py
  solutions/tests/test_multiplication.py
Labels: Challenge

#59 Solution - Text to Morse code
  solutions/tests/test_text_to_morse.py
  solutions/text_to_morse.py
Labels: Solution

#64 Mukuna solution 2
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  solutions/print_triangle_shape.py
  solutions/tests/test_print_triangle_shape.py
Labels: Challenge, Solution

#71 my second challenge
  solutions/celsius_to_fahrenheit.py
  solutions/tests/test_celsius_to_fahrenheit.py
Labels: Challenge, Solution

#54 Solution - Calculate the factorial of a non negative integer
  solutions/calculate_factorial.py
  solutions/tests/test_calculate_factorial.py
Labels: Solution

#86 Tamara's Second Solution: Convert String Characters from Lowercase to Uppercase
  solutions/convert_to_uppercase.py
  solutions/tests/test_convert_to_uppercase.py
Labels: Challenge, Solution

#74 Tamara solution 1- late but perhaps worth the wait?
  solutions/is_odd_or_even.py
  solutions/tests/test_is_odd_or_even.py
Labels: Challenge, Solution

#120 Update README.md
  solutions/README.md
Labels: documentation, enhancement, GOATED

#122 Update test readme
  solutions/tests/README.md
Labels: documentation, enhancement, GOATED

#127 Mahmoud alnouri Challenge 3 - pyramid
  solutions/calculate_pyramid_volume.py
  solutions/tests/test_calculate_pyramid_volume.py
Labels: Challenge
